//------------------------------------------------------------------------------
//  DO NOT EDIT - automatically generated by 'StringTool'
//------------------------------------------------------------------------------

#define S00                                                    0
#define S01                                                    1
#define S02                                                    2
#define S03                                                    3
#define S04                                                    4
#define S05                                                    5
#define S06                                                    6
#define S07                                                    7
#define S08                                                    8
#define S09                                                    9
#define S10                                                   10
#define S11                                                   11
#define S12                                                   12
#define S13                                                   13
#define S14                                                   14
#define S15                                                   15
#define S16                                                   16
#define S17                                                   17
#define S18                                                   18
#define S19                                                   19
#define S20                                                   20
#define S21                                                   21
#define S22                                                   22
#define S23                                                   23
#define S24                                                   24
#define S25                                                   25
#define S26                                                   26
#define S27                                                   27
#define S28                                                   28
#define S29                                                   29
#define S30                                                   30
#define S31                                                   31
#define S32                                                   32
#define S33                                                   33
